import app           from './app';
import { env }        from './config/env';
import { connectDB, disconnectDB } from './config/db';
import { initFirebase } from './config/firebase';
import { initMailer }   from './config/mailer';

const startServer = async (): Promise<void> => {
  await connectDB();
  initFirebase();
  initMailer();

  const server = app.listen(Number(env.PORT), () => {
    console.log('');
    console.log('📚 ─────────────────────────────────────');
    console.log(`🚀  FieldBook API running on port ${env.PORT}`);
    console.log(`🌍  http://localhost:${env.PORT}`);
    console.log(`📦  ENV: ${env.NODE_ENV}`);
    console.log('📚 ─────────────────────────────────────');
    console.log('');
    console.log('  Routes:');
    console.log('  GET  /health');
    console.log('  POST /api/auth/signup');
    console.log('  POST /api/auth/login');
    console.log('  POST /api/auth/refresh');
    console.log('  POST /api/auth/logout');
    console.log('  GET  /api/auth/me');
    console.log('  POST /api/auth/reset-password');
    console.log('  POST /api/auth/forgot-password');
    console.log('  POST /api/auth/reset-password/confirm');
    console.log('  POST /api/notifications/register');
    console.log('  POST /api/notifications/unregister');
    console.log('  POST /api/notifications/send');
    console.log('  GET  /api/schools');
    console.log('  GET  /api/classes');
    console.log('  POST /api/classes');
    console.log('  PATCH /api/classes/:classId');
    console.log('  DELETE /api/classes/:classId');
    console.log('  POST /api/classes/:classId/sections');
    console.log('  PATCH /api/classes/:classId/sections/:sectionId');
    console.log('  DELETE /api/classes/:classId/sections/:sectionId');
    console.log('  POST /api/classes/:classId/subjects');
    console.log('  GET  /api/subjects');
    console.log('  POST /api/subjects');
    console.log('  POST /api/admin/students');
    console.log('  GET  /api/admin/students');
    console.log('  GET  /api/admin/students/:studentId');
    console.log('  PATCH /api/admin/students/:studentId');
    console.log('  POST /api/admin/teachers');
    console.log('  GET  /api/admin/teachers');
    console.log('  GET  /api/admin/teachers/:teacherId');
    console.log('  PATCH /api/admin/teachers/:teacherId');
    console.log('  POST /api/admin/teachers/:teacherId/subjects');
    console.log('  DELETE /api/admin/teachers/:teacherId/subjects/:subjectId/:classId');
    console.log('  POST /api/admin/announcements');
    console.log('  GET  /api/admin/announcements');
    console.log('  GET  /api/admin/announcements/:announcementId');
    console.log('  PATCH /api/admin/announcements/:announcementId');
    console.log('  DELETE /api/admin/announcements/:announcementId');
    console.log('  POST /api/admin/events');
    console.log('  GET  /api/admin/events');
    console.log('  GET  /api/admin/events/:eventId');
    console.log('  PATCH /api/admin/events/:eventId');
    console.log('  DELETE /api/admin/events/:eventId');
    console.log('  POST /api/admin/exams');
    console.log('  GET  /api/admin/exams');
    console.log('  GET  /api/admin/exams/:examId');
    console.log('  PATCH /api/admin/exams/:examId');
    console.log('  DELETE /api/admin/exams/:examId');
    console.log('  POST /api/admin/exams/:examId/classes');
    console.log('  GET  /api/admin/exams/:examId/classes');
    console.log('  DELETE /api/admin/exams/:examId/classes/:classId');
    console.log('  GET  /api/admin/exams/:examId/classes/:classId/students');
    console.log('  POST /api/admin/exams/:examId/results');
    console.log('  GET  /api/admin/exams/:examId/results/:resultId');
    console.log('  PATCH /api/admin/exams/:examId/results/:resultId');
    console.log('  DELETE /api/admin/exams/:examId/results/:resultId');
    console.log('  GET  /api/admin/attendance/classes');
    console.log('  GET  /api/admin/attendance/classes/:classId/students');
    console.log('  POST /api/admin/schedule');
    console.log('  GET  /api/admin/schedule');
    console.log('  GET  /api/admin/schedule/:scheduleId');
    console.log('  PATCH /api/admin/schedule/:scheduleId');
    console.log('  DELETE /api/admin/schedule/:scheduleId');
    console.log('  GET  /api/admin/schedule/sections/:sectionId');
    console.log('  GET  /api/admin/schedule/teachers/:teacherId');
    console.log('  GET  /api/admin/leave');
    console.log('  PATCH /api/admin/leave/:leaveId');
    console.log('  GET  /api/admin/leave/teachers');
    console.log('  PATCH /api/admin/leave/teachers/:leaveId');
    console.log('  POST /api/admin/teacher-attendance');
    console.log('  GET  /api/admin/teacher-attendance');
    console.log('  PATCH /api/admin/teacher-attendance/:recordId');
    console.log('  POST /api/admin/staff');
    console.log('  GET  /api/admin/staff');
    console.log('  GET  /api/admin/staff/:staffId');
    console.log('  PATCH /api/admin/staff/:staffId');
    console.log('  DELETE /api/admin/staff/:staffId');
    console.log('  GET  /api/admin/dashboard');
    console.log('  GET  /api/teacher/dashboard');
    console.log('  GET  /api/teacher/profile');
    console.log('  PATCH /api/teacher/profile');
    console.log('  POST /api/teacher/reset-password');
    console.log('  GET  /api/teacher/classes');
    console.log('  GET  /api/teacher/students');
    console.log('  GET  /api/teacher/announcements');
    console.log('  GET  /api/teacher/events');
    console.log('  GET  /api/teacher/schedule/today');
    console.log('  GET  /api/teacher/schedule/week');
    console.log('  GET  /api/teacher/attendance');
    console.log('  POST /api/teacher/attendance');
    console.log('  GET  /api/teacher/attendance/students/:studentId');
    console.log('  PATCH /api/teacher/attendance/:recordId');
    console.log('  GET  /api/teacher/my-attendance');
    console.log('  POST /api/teacher/homework');
    console.log('  GET  /api/teacher/homework');
    console.log('  GET  /api/teacher/homework/:homeworkId');
    console.log('  PATCH /api/teacher/homework/:homeworkId');
    console.log('  DELETE /api/teacher/homework/:homeworkId');
    console.log('  GET  /api/teacher/homework/:homeworkId/students');
    console.log('  PATCH /api/teacher/homework/:homeworkId/students');
    console.log('  GET  /api/teacher/leave');
    console.log('  PATCH /api/teacher/leave/:leaveId');
    console.log('  POST /api/teacher/my-leave');
    console.log('  GET  /api/teacher/my-leave');
    console.log('  DELETE /api/teacher/my-leave/:leaveId');
    console.log('  GET  /api/students/dashboard');
    console.log('  GET  /api/students/profile');
    console.log('  PATCH /api/students/profile');
    console.log('  POST /api/students/reset-password');
    console.log('  GET  /api/students/announcements');
    console.log('  GET  /api/students/events');
    console.log('  GET  /api/students/exams');
    console.log('  GET  /api/students/exams/:examId');
    console.log('  GET  /api/students/timetable');
    console.log('  GET  /api/students/attendance');
    console.log('  POST /api/students/leave');
    console.log('  GET  /api/students/leave');
    console.log('  DELETE /api/students/leave/:leaveId');
    console.log('  GET  /api/students/homework');
    console.log('  GET  /api/students/homework/:homeworkId');
    console.log('  POST /api/super-admin/schools');
    console.log('  GET  /api/super-admin/schools');
    console.log('  GET  /api/super-admin/schools/:schoolId');
    console.log('  PATCH /api/super-admin/schools/:schoolId');
    console.log('  POST /api/super-admin/schools/:schoolId/admins');
    console.log('  GET  /api/super-admin/schools/:schoolId/admins');
    console.log('  PATCH /api/super-admin/schools/:schoolId/admins/:adminId');
    console.log('  PATCH /api/super-admin/schools/:schoolId/admins/:adminId/status');
    console.log('  GET  /api/super-admin/admins');
    console.log('');
  });

  // ── Graceful shutdown ──────────────────────────────────────
  const shutdown = async (signal: string) => {
    console.log(`\n${signal} received — shutting down gracefully...`);
    server.close(async () => {
      await disconnectDB();
      console.log('✅ Server closed');
      process.exit(0);
    });
  };

  process.on('SIGTERM', () => shutdown('SIGTERM'));
  process.on('SIGINT',  () => shutdown('SIGINT'));
};

startServer().catch(err => {
  console.error('❌ Failed to start server:', err);
  process.exit(1);
});
